### PR TITLE
Add NCAAMB wrappers

### PR DESCRIPTION
**Pull request by ConnerPhillis**
This adds wrapper methods for the NCAAMB set of APIs on Sportradar.

### CODE REVIEW

**Comment by johnwmillr** [comment]
Thank you for this PR! Do you mind writing the corresponding `tests/test_NCAAMB.py` file? It should be straightforward to follow the format of the other test files.

**Comment by ConnerPhillis** [comment]
@johnwmillr Yep, sorry, I wrote them and it looks like I forgot to stage it in the commit, thanks for taking a look at it!

**Comment by johnwmillr** [comment]
Hi @ConnerPhillis, not sure if you're waiting to add them, but your latest commit only added import statements to the test file, not the tests themselves.

**Comment by ConnerPhillis** [comment]
@johnwmillr 

Yep, sorry, turns out I was a complete idiot when I was staging these files. Instead of adding the tests I actually removed them without thinking, then I staged a file that I mean to delete in place of them. I've rewritten them and they should be in the latest commit.

**Pull request merged**
